### ISSUE TITLE
Time format of observation date in soil site data?

### ISSUE THREAD

**Issue by AubinAllies** [soilspectroscopy/ossl-imports#2] opened 2021-12-21 09:03 UTC
Hello

I recently downloaded soil attributes data on OSSL but the observation date in the soilsite.data.csv file do not match the ISO8601 time format (yyyy.mm.dd). Indeed, observation dates are ranking between 11651 and 18591. Could you please give me the way to convert this data in the yyyy.mm.dd type.

Thank you in advance

**Comment by thengl** [comment] 2021-12-21 09:14
The issue is with the KSSL dataset. I will look again at [the import steps](https://github.com/soilspectroscopy/ossl-imports/blob/main/dataset/KSSL/README.rmd#L274) and come back to you. Unfortunately KSSL only has Year of observation, no months days.

**Comment by thengl** [comment] 2022-01-06 12:20
The mistake has now been fixed with https://github.com/soilspectroscopy/ossl-imports/commit/655550daf9162b0d5a81e38a5d9037c0fa5af30f. The problem was with using rbind.fill function that unfortunately [strips the dates if one column is Date, other character](https://stackoverflow.com/questions/29986950/rbind-fill-columns-of-different-classes).

**Closed as completed by thengl** 2022-01-06 12:20 UTC
Labels: KSSL
